# Generated by Django 3.2.9 on 2021-11-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20211112_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30, verbose_name='Имя')),
                ('second_name', models.CharField(default='', max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(default='', max_length=30, unique=True, verbose_name='Электронная почта')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('uuid', models.TextField(default='', verbose_name='uuid')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['second_name'],
            },
        ),
        migrations.AlterField(
            model_name='auth',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='auth', to='board.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bill', to='board.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userdevices',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='UserDevices', to='board.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='visit', to='board.user', verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
