# Generated by Django 3.2.9 on 2021-11-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20211112_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.TextField(default='', unique=True, verbose_name='uuid'),
        ),
    ]
