# Generated by Django 3.2.9 on 2021-11-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='seat_number',
            field=models.IntegerField(default='', unique=True, verbose_name='Номер шезлонга'),
        ),
    ]
